server {
    listen 80;
    listen [::]:80;
    server_name dimkolya.ru www.dimkolya.ru dimkolya.online www.dimkolya.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name dimkolya.ru www.dimkolya.ru;

    ssl_certificate /etc/letsencrypt/live/dimkolya.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dimkolya.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/dimkolya-backend-proxy.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name dimkolya.online www.dimkolya.online;

    ssl_certificate /etc/letsencrypt/live/dimkolya.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dimkolya.online/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/dimkolya-backend-proxy.conf;
}
